### ISSUE TITLE
Crystal rocks

### ISSUE THREAD

**Issue by bcardiff** [Nardoz/charlas#11]
### Título
Crystal rocks

### Descripción

Una efectiva introducción al lenguaje para entender sus fundamentos y virtudes. Conoceremos también parte del ecosistema actual para hacer distintos tipos de aplicaciones y en qué situaciones se puede tener ventajas al usar Crystal.

### Bio

En el ámbito de la programación, tengo mayor experiencia en .Net y Ruby. Hoy en día mi mayor dedicación es en Crystal. Me gusta usar Haskell y Prolog tanto como puedo. Me gradué en Ciencias de la Computación en FCEyN en el campo de métodos formales. Además de disfrutar los aspectos formales de una solución, valoro mucho las visualizaciones, los detalles y la experiencia de usuario. Para mantenerme alejado del teclado, me encuentran en las pistas de baile social de Blues y Swing.

**Comment by opensas** [comment]
bravo!!!!!

**Comment by bcardiff** [comment]
Slides: https://www.slideshare.net/BrianCardiff/crystal-rocks
