### ISSUE TITLE
¿Cascading Style Sheets o Caca Sin Sentido?

### ISSUE THREAD

**Issue by v13j0** [Nardoz/charlas#14]
### ¿Cascading Style Sheets o Caca Sin Sentido?

Alguna vez te pasó que cambiaste un estilo inocente en un componente random totalmente inofensivo y luego de testear y chequear el PR cual demente, le QA te lo rebota porque te rompió otra cosa en la otra punta de la app que ni sabías que existía? Bueno, entonces esta charla es para vos. 

Con el método **csscat** vamos a aprender a pensar los estilos laburando con React (y sin React también) de modo tal que el css de nuestro proyecto no se vuelva una **caca** infumable de selectores interminables, bocha de falopa y especificidad incontrolable.

**Comment by palamago** [comment]
Me encantaría ver esta charla !! 💩 😄

**Comment by gvilarino** [comment]
Venite @palamago, no te fajamos más
