### ISSUE TITLE
Programación defensiva en Node con PureScript

### ISSUE THREAD

**Issue by hrajchert** [Nardoz/charlas#2]
# Título
Programación defensiva en Node con PureScript

# Descripción
Cuando programamos nuestra primera intuición suele ser resolver "el camino feliz", hacer la tarea que tenemos que hacer suponiendo que todo es como esperamos, que nada falla. Lamentablemente "todo el software está roto" y en general los bugs no están en el camino feliz. Tenemos que programar defensivamente!

En esta charla vamos a presentar una pequeña prueba de concepto de una herramienta de consola hecha tanto en JavaScript como en PureScript concentrandonos en particular en todas las cosas que pueden malir sal y qué podemos hacer para agarrar todos los errores y que no se nos escape ningún bug.

# Bio
Ingeniero en Informática enfocado en tecnologías web. Trabajo tanto en el front como en el back, me gusta la programación funcional y los lenguajes tipados. CTO en Acámica.

**Comment by gvilarino** [comment]
Me copa, me copa!

**Comment by matiasurbano** [comment]
Muy interesante el topic, pueden grabar las charlas @gvilarino @hrajchert ?  por la diferencia horaria y distancia me va a costar asistir personalmente,  estoy en 🇦🇺 
Cheers :)

**Comment by gvilarino** [comment]
Haremos todo lo posible por grabarlas y/o stremearlas :)
