### ISSUE TITLE
Rompiendo Mitos: Síndrome del impostor, sobreexigencia, stress... Alguien por favor piensa en lxs Devs??!!

### ISSUE THREAD

**Issue by alphacentauri82** [Nardoz/charlas#3]
### Título
Rompiendo Mitos: Síndrome del impostor, sobreexigencia, stress... Alguien por favor piensa en lxs Devs??!!

### Descripción
Una pared con la que chocamos en algún momento de nuestra existencia. Compartiremos algunas estrategias para hacerle frente a estos asuntos y no quemarnos en el intento!

### Bio
Mujer. Venezolana. Dev/DevOps. Pienso mucho, Pregunto mucho, me río mucho. Me gusta aprender y compartir experiencias.

**Comment by marcote** [comment]
Yo creo que es algo de mucho valor esta charla sobre todo para gente que da sus primeros pasos.
